version: '3'
services:
  redis-server:
    image: "redis"
  node-app:
    build: .
    ports:
      - "4001:8081"

# After creating the docker compose yaml file, you can run the following command in the terminal.
#  docker compose up
