version: '3'
services:
  redis-server:
    image: "redis"
  node-app:
    build: .
    ports:
      - "4001:8081"

# after the docker compose yaml file creation, we can use the below command in terminal
#  docker compose up