FROM node:alpine
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
CMD ["npm", "start"]

# docker build -t react-img -f Dockerfile.dev .

# container with docker volumes,using the below command:
# docker run -d -p 3000:3000 -v /app/node_modules -v $(pwd):/app (con_id)

# After running above command, use below url from browser
# localhost:3000